engines:
  eslint:
    enabled: true
    config: .eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  csslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO

ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - python
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
exclude_paths:
  - "backend/public"
  - "frontend/public"
  - "frontend/node_modules"
