language: python
python:
  - 3.4
  - 3.5
  - 3.6
node_js:
  - 6
env:
  - NODE_VERSION=6
  - NODE_VERSION=7
before_install:
  - sudo apt-get install libjpeg-dev
  - . $HOME/.nvm/nvm.sh
  - nvm install $NODE_VERSION
install:
  - pip3 install -r backend/requirements.txt
  - npm install npm -g
  - pushd frontend && npm install && popd
before_script:
  - flake8 --exclude=settings.py,migrations backend/
  - psql -c "CREATE USER pjunb WITH createdb PASSWORD 'integration_build';" -U postgres
  - psql -c 'CREATE DATABASE funbox OWNER pjunb;' -U postgres
  - echo '{"status":"done","chunks":{"main":[]}}' > frontend/webpack-stats.json
script:
  - python3 backend/manage.py makemigrations
  - python3 backend/manage.py migrate
  - pushd backend
  - pytest --cov-report term-missing --verbose --cov-config .coveragerc --cov
  - mv .coverage ../
  - popd && pushd frontend
# - ./node_modules/eslint/bin/eslint.js
  - npm test
  - popd
after_success: coveralls
services:
  - postgresql
branch:
  only:
    - master
    - devel
